### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by willy-r** [willy-r/simple-mooc#3]
Algumas ideias sobre o que fazer em seguida, sem necessariamente nessa ordem e se não der pra fazer marcar como incompleta. Essa Issue pode ser atualizada constantemente.

- [ ] Melhorar o sistema de administração, como por exemplo impedir que contas de instrutores possam acessar outros cursos que não os deles mesmo.
- [ ] Melhorar as configurações de deploy, criar um arquivo separado para configurações de desenvolvimento.
- [ ] Criar o sistema de fórum para a interação dos estudantes/administradores/instrutores.
- [ ] Redimensionar as imagens dos cursos para 400x250 depois do upload dos usuários e colocar uma mensagem de ajuda avisando sobre o redimensiomento.
